CREATE PROCEDURE [dbo].[SP_GRUPO] AS
BEGIN
	DECLARE @COD_BOLAO INT
	DECLARE @DSC_BOLAO VARCHAR(100)
	DECLARE @DAT_RANKING DATETIME
	DECLARE @COD_FASE INT
	DECLARE @COD_JOGO INT
	DECLARE @COD_GRUPO INT
	DECLARE @VLR_PONTUACAO INT
	DECLARE @DSC_REGRA VARCHAR(1000)
	DECLARE @SQL NVARCHAR(4000)
	BEGIN TRAN
	DECLARE CSR_BOLAO CURSOR FOR
		SELECT B.COD_BOLAO
		FROM BOLAO B
		WHERE B.IND_STATUS = 'A'
		ORDER BY B.COD_BOLAO ASC
	OPEN CSR_BOLAO
	FETCH NEXT FROM CSR_BOLAO INTO @COD_BOLAO
	WHILE @@FETCH_STATUS = 0 BEGIN
		DECLARE CSR_FASE CURSOR FOR
			SELECT F.COD_FASE
			FROM FASE F
			WHERE F.IND_STATUS IN ('A', 'F') AND F.COD_BOLAO = @COD_BOLAO
			ORDER BY F.COD_FASE
		OPEN CSR_FASE
		FETCH NEXT FROM CSR_FASE INTO @COD_FASE
		WHILE @@FETCH_STATUS = 0 BEGIN
			DECLARE CSR_GRUPO CURSOR FOR
				SELECT G.COD_GRUPO
				FROM GRUPO G
				WHERE G.COD_FASE = @COD_FASE AND G.COD_BOLAO = @COD_BOLAO
				ORDER BY G.COD_GRUPO
			OPEN CSR_GRUPO
			FETCH NEXT FROM CSR_GRUPO INTO @COD_GRUPO
			WHILE @@FETCH_STATUS = 0 BEGIN
				UPDATE TIME_GRUPO SET
					IND_CLASSIFICADO = 'N',
					QTD_VITORIA = 
						(SELECT COUNT(*) FROM JOGO WHERE ((TIME_GRUPO.COD_TIME = JOGO.COD_TIME_A AND JOGO.QTD_GOL_A > JOGO.QTD_GOL_B) OR (TIME_GRUPO.COD_TIME = JOGO.COD_TIME_B AND JOGO.QTD_GOL_B > JOGO.QTD_GOL_A)) AND JOGO.COD_GRUPO = TIME_GRUPO.COD_GRUPO AND JOGO.IND_REALIZADO = 'S'),
					QTD_EMPATE = 					
						(SELECT COUNT(*) FROM JOGO WHERE (TIME_GRUPO.COD_TIME = JOGO.COD_TIME_A OR TIME_GRUPO.COD_TIME = JOGO.COD_TIME_B) AND JOGO.QTD_GOL_A = JOGO.QTD_GOL_B AND JOGO.COD_GRUPO = TIME_GRUPO.COD_GRUPO AND JOGO.IND_REALIZADO = 'S'),
					QTD_DERROTA = 
						(SELECT COUNT(*) FROM JOGO WHERE ((TIME_GRUPO.COD_TIME = JOGO.COD_TIME_B AND JOGO.QTD_GOL_A > JOGO.QTD_GOL_B) OR (TIME_GRUPO.COD_TIME = JOGO.COD_TIME_A AND JOGO.QTD_GOL_B > JOGO.QTD_GOL_A)) AND JOGO.COD_GRUPO = TIME_GRUPO.COD_GRUPO AND JOGO.IND_REALIZADO = 'S'),
					QTD_GOL_FEITO = 0 +
						COALESCE((SELECT SUM(JOGO.QTD_GOL_A) FROM JOGO WHERE TIME_GRUPO.COD_TIME = JOGO.COD_TIME_A AND JOGO.COD_GRUPO = TIME_GRUPO.COD_GRUPO AND JOGO.IND_REALIZADO = 'S'), 0) +
						COALESCE((SELECT SUM(JOGO.QTD_GOL_B) FROM JOGO WHERE TIME_GRUPO.COD_TIME = JOGO.COD_TIME_B AND JOGO.COD_GRUPO = TIME_GRUPO.COD_GRUPO AND JOGO.IND_REALIZADO = 'S'), 0),
					QTD_GOL_SOFRIDO = 0 +
						COALESCE((SELECT SUM(JOGO.QTD_GOL_B) FROM JOGO WHERE TIME_GRUPO.COD_TIME = JOGO.COD_TIME_A AND JOGO.COD_GRUPO = TIME_GRUPO.COD_GRUPO AND JOGO.IND_REALIZADO = 'S'), 0) +
						COALESCE((SELECT SUM(JOGO.QTD_GOL_A) FROM JOGO WHERE TIME_GRUPO.COD_TIME = JOGO.COD_TIME_B AND JOGO.COD_GRUPO = TIME_GRUPO.COD_GRUPO AND JOGO.IND_REALIZADO = 'S'), 0)
				WHERE COD_GRUPO = @COD_GRUPO 
				UPDATE TIME_GRUPO SET 
					QTD_PONTO = 3 * QTD_VITORIA + 1 * QTD_EMPATE + 0 * QTD_DERROTA
				WHERE COD_GRUPO = @COD_GRUPO
				UPDATE TIME_GRUPO 
				SET IND_CLASSIFICADO = 'S' 
				FROM TIME_GRUPO A, 
					(SELECT TOP 2 B.COD_TIME 
					FROM TIME_GRUPO B 
						INNER JOIN TIME C ON B.COD_TIME = C.COD_TIME
					WHERE B.COD_GRUPO = @COD_GRUPO 
					ORDER BY B.QTD_PONTO DESC, B.QTD_VITORIA DESC, (B.QTD_GOL_FEITO - B.QTD_GOL_SOFRIDO) DESC, B.QTD_GOL_FEITO DESC, C.NOM_TIME ASC) B
				WHERE A.COD_TIME = B.COD_TIME AND
					A.COD_GRUPO = @COD_GRUPO
				FETCH NEXT FROM CSR_GRUPO INTO @COD_GRUPO
			END
			CLOSE CSR_GRUPO
			DEALLOCATE CSR_GRUPO
			FETCH NEXT FROM CSR_FASE INTO @COD_FASE
		END
		CLOSE CSR_FASE
		DEALLOCATE CSR_FASE
		FETCH NEXT FROM CSR_BOLAO INTO @COD_BOLAO
	END
	CLOSE CSR_BOLAO
	DEALLOCATE CSR_BOLAO
	COMMIT TRAN
	
END
