CREATE TABLE [dbo].[CRITERIO] (
    [COD_CRITERIO]  INT            NOT NULL,
    [DSC_CRITERIO]  VARCHAR (50)   NOT NULL,
    [VLR_PONTUACAO] INT            NOT NULL,
    [DSC_REGRA]     VARCHAR (1500) NOT NULL, 
    CONSTRAINT [PK_CRITERIO] PRIMARY KEY ([COD_CRITERIO])
);

