CREATE TABLE [dbo].[JOGO] (
    [COD_JOGO]          INT           IDENTITY (1, 1) NOT NULL,
    [COD_FASE]          INT           NOT NULL,
    [COD_BOLAO]         INT           NOT NULL,
    [COD_GRUPO]         INT           NOT NULL,
    [COD_TIME_A]        INT           NOT NULL,
    [COD_TIME_B]        INT           NOT NULL,
    [NUM_JOGO]          INT           NOT NULL,
    [QTD_GOL_A]         INT           NULL,
    [QTD_GOL_B]         INT           NULL,
    [DAT_JOGO]          DATETIME      NOT NULL,
    [DSC_LOCAL]         VARCHAR (100) NOT NULL,
    [DSC_ESTADIO]       VARCHAR (100) NULL,
    [IND_REALIZADO]     CHAR (1)      NOT NULL DEFAULT 'N'
		CONSTRAINT FK_JOGO_IND_REALIZADO CHECK (IND_REALIZADO IN ('S', 'N')),
    [DAT_LIMITE_APOSTA] DATETIME      NULL, 
    CONSTRAINT [PK_JOGO] PRIMARY KEY ([COD_JOGO])
);
GO

ALTER TABLE JOGO ADD CONSTRAINT FK_FASE_JOGO_01 FOREIGN KEY (COD_FASE) REFERENCES FASE (COD_FASE)
GO

ALTER TABLE JOGO ADD CONSTRAINT FK_BOLAO_JOGO_01 FOREIGN KEY (COD_BOLAO) REFERENCES BOLAO (COD_BOLAO)
GO

ALTER TABLE JOGO ADD CONSTRAINT FK_GRUPO_JOGO_01 FOREIGN KEY (COD_GRUPO) REFERENCES GRUPO (COD_GRUPO)
GO

ALTER TABLE JOGO ADD CONSTRAINT FK_TIME_JOGO_01 FOREIGN KEY (COD_TIME_A) REFERENCES TIME (COD_TIME)
GO

ALTER TABLE JOGO ADD CONSTRAINT FK_TIME_JOGO_02 FOREIGN KEY (COD_TIME_B) REFERENCES TIME (COD_TIME)
GO

CREATE INDEX IDX_JOGO_001 ON JOGO (COD_FASE)
GO

CREATE INDEX IDX_JOGO_002 ON JOGO (COD_BOLAO)
GO

CREATE INDEX IDX_JOGO_003 ON JOGO (COD_GRUPO)
GO

CREATE INDEX IDX_JOGO_004 ON JOGO (COD_TIME_A)
GO

CREATE INDEX IDX_JOGO_005 ON JOGO (COD_TIME_B)
GO
