CREATE TABLE [dbo].[LOG_REGISTRO] (
    [COD_LOG_REGISTRO]      BIGINT        IDENTITY (1, 1) NOT NULL,
    [DAT_LOG_REGISTRO]      DATETIME      NOT NULL,
    [COD_USUARIO]           INT           NULL,
    [NOM_TABELA]            VARCHAR (100) NOT NULL,
    [IND_TIPO_LOG_REGISTRO] CHAR (1)      NOT NULL,
    [DSC_DADOS_ANTES]       XML           NULL,
    [DSC_DADOS_DEPOIS]      XML           NULL,
    [DSC_ATRIBUTO]          XML           NULL,
    CONSTRAINT [PK_LOGREGISTRO] PRIMARY KEY CLUSTERED ([COD_LOG_REGISTRO] ASC),
	CONSTRAINT FK_USUARIO_LOGREGISTRO_01 FOREIGN KEY (COD_USUARIO) REFERENCES USUARIO (COD_USUARIO)
);
GO

CREATE INDEX IDX_LOGREGISTRO_001 ON LOG_REGISTRO (COD_USUARIO)
GO
