CREATE TABLE [dbo].[PARTICIPANTE] (
    [COD_USUARIO]       INT      NOT NULL,
    [COD_BOLAO]         INT      NOT NULL,
    [VLR_PONTUACAO]     INT      NOT NULL,
    [NUM_RANKING]       INT      NOT NULL,
    [IND_ADMINISTRADOR] CHAR (1) NOT NULL DEFAULT 'N'
		CONSTRAINT CK_BOLAO_IND_ADMINISTRADOR CHECK (IND_ADMINISTRADOR IN ('S', 'N')),
    [IND_BOLAO_PAGO]    CHAR (1) NOT NULL DEFAULT 'N'
		CONSTRAINT CK_BOLAO_IND_BOLAO_PAGO CHECK (IND_BOLAO_PAGO IN ('S', 'N')),
    [DAT_CADASTRO] DATETIME NOT NULL DEFAULT getdate(), 
    [DAT_MODIFICACAO] DATETIME NOT NULL DEFAULT getdate(), 
    CONSTRAINT [PK_PARTICIPANTE] PRIMARY KEY CLUSTERED ([COD_USUARIO] ASC, [COD_BOLAO] ASC),
    CONSTRAINT [FK_USUARIO_PARTICIPANTE_01] FOREIGN KEY ([COD_USUARIO]) REFERENCES [dbo].[USUARIO] ([COD_USUARIO]),
    CONSTRAINT [FK_USUARIO_PARTICIPANTE_02] FOREIGN KEY ([COD_BOLAO]) REFERENCES [dbo].[BOLAO] ([COD_BOLAO])
);
GO

CREATE INDEX IDX_PARTICIPANTE_001 ON PARTICIPANTE (COD_BOLAO)
GO
