CREATE TABLE [dbo].[TIME_GRUPO] (
    [COD_TIME]         INT      NOT NULL,
    [COD_GRUPO]        INT      NOT NULL,
    [QTD_VITORIA]      INT      NOT NULL,
    [QTD_EMPATE]       INT      NOT NULL,
    [QTD_DERROTA]      INT      NOT NULL,
    [QTD_PONTO]        INT      NOT NULL,
    [QTD_GOL_FEITO]    INT      NOT NULL,
    [QTD_GOL_SOFRIDO]  INT      NOT NULL,
    [IND_CLASSIFICADO] CHAR (1) NOT NULL DEFAULT 'N'
		CONSTRAINT CK_TIMEGRUPO_IND_CLASSIFICADO CHECK (IND_CLASSIFICADO IN ('N', 'S')),
    CONSTRAINT [PK_TIMEGRUPO] PRIMARY KEY CLUSTERED ([COD_TIME] ASC, [COD_GRUPO] ASC),
    CONSTRAINT [FK_GRUPO_TIMEGRUPO_01] FOREIGN KEY ([COD_GRUPO]) REFERENCES [dbo].[GRUPO] ([COD_GRUPO]),
    CONSTRAINT [FK_TIME_TIMEGRUPO_01] FOREIGN KEY ([COD_TIME]) REFERENCES [dbo].[TIME] ([COD_TIME])
);
GO

CREATE INDEX IDX_TIMEGRUPO_001 ON TIME_GRUPO (COD_GRUPO)
GO

CREATE INDEX IDX_TIMEGRUPO_002 ON TIME_GRUPO (COD_TIME)
GO

