CREATE TABLE [dbo].[TIME] (
    [COD_TIME]  INT           IDENTITY (1, 1) NOT NULL,
    [NOM_TIME]  VARCHAR (50)  NOT NULL,
    [SGL_TIME]  CHAR (3)      NULL,
    [DSC_ICONE] VARCHAR (100) NULL,
    CONSTRAINT [PK_TIME] PRIMARY KEY CLUSTERED ([COD_TIME] ASC)
);

