CREATE TABLE [dbo].[USUARIO] (
    [COD_USUARIO]  INT           IDENTITY (1, 1) NOT NULL,
	[IND_ATIVO]    CHAR(1) NOT NULL DEFAULT 'S'
		CONSTRAINT CK_USUARIO_IND_ATIVO CHECK (IND_ATIVO IN ('S', 'N')),
    [NOM_USUARIO]  VARCHAR (100) NULL,
    [DSC_EMAIL]    VARCHAR (100) NOT NULL,
    [DSC_SENHA] NVARCHAR(1000) NULL, 
    [DAT_CADASTRO] DATETIME NOT NULL DEFAULT getdate(),
    [DAT_MODIFICACAO] DATETIME NOT NULL DEFAULT getdate(), 
    CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED ([COD_USUARIO] ASC)
);

